# Generated by Django 5.1.4 on 2024-12-08 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('MOUSE', 'Mouse'), ('KEYBOARD', 'Keyboard'), ('RAM', 'RAM'), ('HARD-DISK', 'Hard Disk'), ('WINDOWS 11', 'Windows 11'), ('WINDOWS 10', 'Windows 10'), ('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('MOBILE CHARGER', 'Mobile Charger'), ('LAPTOP CHARGER', 'Laptop Charger')], max_length=20)),
            ],
        ),
    ]
